plugins:
  guest_gate_enabled:
    default: true
    client: true
  max_guest_topic_views:
    default: 1
    client: true
  x_button_disabled:
    default: true
    client: false
  gate_show_only_once:
    default: false
    client: false
  custom_gate_enabled:
    default: true
    client: false
  custom_gate_image_url:
    type: text
    default: 'https://careerninja.in/wp-content/uploads/2019/02/Logo-unit-_-white-BG-copy-1.png'
    client: false
  custom_gate_big_text:
    type: text
    default: 'Please Sign Up'
    client: false
  custom_gate_big_text_color:
    type: text
    default: '#aaa'
    client: false
  custom_gate_little_text:
    type: text
    default: 'careerninja.in'
    client: false
  custom_gate_little_text_color:
    type: text
    default: '#aaa'
    client: false
  custom_gate_background_color:
    type: text
    default: '#FFFFFF'
    client: false
  custom_gate_link_color:
    type: text
    default: '#aaa'
    client: false
